// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/apachet.mdl
models/cracklife/barney.mdl
models/cracklife/gman.mdl
models/cracklife/scientist.mdl
sound/cracklife/ambience/alienflyby1.wav
sound/cracklife/ambience/biggun1.wav
sound/cracklife/ambience/computalk1.wav
sound/cracklife/ambience/waterfall1.wav
sound/cracklife/ambience/wind1.wav
sound/cracklife/apache/ap_rotor1.wav
sound/cracklife/barney/ba_pain1.wav
sound/cracklife/barney/c1a0_ba_late.wav
sound/cracklife/buttons/blip1.wav
sound/cracklife/buttons/button1.wav
sound/cracklife/buttons/button3.wav
sound/cracklife/buttons/button6.wav
sound/cracklife/buttons/latchlocked1.wav
sound/cracklife/buttons/latchunlocked1.wav
sound/cracklife/buttons/latchunlocked2.wav
sound/cracklife/common/npc_step1.wav
sound/cracklife/common/npc_step2.wav
sound/cracklife/debris/bustceiling.wav
sound/cracklife/debris/bustcrate1.wav
sound/cracklife/doors/doormove1.wav
sound/cracklife/doors/doormove2.wav
sound/cracklife/doors/doormove3.wav
sound/cracklife/plats/bigstop1.wav
sound/cracklife/player/pl_metal1.wav
sound/cracklife/player/pl_metal2.wav
sound/cracklife/player/pl_metal4.wav
sound/cracklife/scientist/c1a0_sci_catscream.wav
sound/cracklife/scientist/c1a0_sci_stayback.wav
sound/cracklife/scientist/c1a2_sci_dangling.wav
sound/cracklife/scientist/c1a4_sci_rocket.wav
sound/cracklife/scientist/c1a4_sci_tent.wav
sound/cracklife/tride/c0a0_tr_arrive.wav
sound/cracklife/tride/c0a0_tr_dest.wav
sound/cracklife/tride/c0a0_tr_emerg.wav
sound/cracklife/tride/c0a0_tr_exit.wav
sound/cracklife/tride/c0a0_tr_gmorn.wav
sound/cracklife/tride/c0a0_tr_haz.wav
sound/cracklife/tride/c0a0_tr_jobs.wav
sound/cracklife/tride/c0a0_tr_noeat.wav
sound/cracklife/tride/c0a0_tr_time.wav
sound/cracklife/tride/c0a0_tr_tourn.wav
